services:
  - type: web
    name: smart-cough-backend
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
